version: '3.8'

services:
  xray-calculator:
    build: .
    container_name: xray-calculator
    ports:
      - "5000:8501"
    volumes:
      - ./processed_nist_xcom_data:/app/processed_nist_xcom_data
      - ./tmp_plots:/app/tmp_plots
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: "60s"
      timeout: "10s"
      retries: 3
    environment:
      PYTHONUNBUFFERED: "1" 